#:kivy 1.0
#: import WipeTransition kivy.uix.screenmanager.WipeTransition
#: import CardTransition kivy.uix.screenmanager.CardTransition
#: import SwapTransition kivy.uix.screenmanager.SwapTransition
#: import FadeTransition kivy.uix.screenmanager.FadeTransition
#: import FallOutTransition kivy.uix.screenmanager.FallOutTransition
#: import RiseInTransition kivy.uix.screenmanager.RiseInTransition

<WindowManager>:
    MainWindow:
    MotorWindow:
    MotorDataSettingWindow:
